# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: naturalengine.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13naturalengine.proto"(\n\x05\x45vent\x12\x1f\n\nevent_type\x18\x01 \x01(\x0e\x32\x0b.Event_Type",\n\x10NewEventResponse\x12\x18\n\x07threats\x18\x01 \x03(\x0b\x32\x07.Threat"+\n\x06Threat\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bthreat_type\x18\x02 \x01(\t*A\n\nEvent_Type\x12\t\n\x05\x41SSET\x10\x00\x12\x0c\n\x08WORKFLOW\x10\x01\x12\n\n\x06THREAT\x10\x02\x12\x0e\n\nMITIGATION\x10\x03\x32\x36\n\rNaturalEngine\x12%\n\x08NewEvent\x12\x06.Event\x1a\x11.NewEventResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "naturalengine_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_EVENT_TYPE"]._serialized_start = 156
    _globals["_EVENT_TYPE"]._serialized_end = 221
    _globals["_EVENT"]._serialized_start = 23
    _globals["_EVENT"]._serialized_end = 63
    _globals["_NEWEVENTRESPONSE"]._serialized_start = 65
    _globals["_NEWEVENTRESPONSE"]._serialized_end = 109
    _globals["_THREAT"]._serialized_start = 111
    _globals["_THREAT"]._serialized_end = 154
    _globals["_NATURALENGINE"]._serialized_start = 223
    _globals["_NATURALENGINE"]._serialized_end = 277
# @@protoc_insertion_point(module_scope)
